{{- if and .Values.mgmt.enabled .Values.mgmt.ingress.enabled -}}
{{- $fullName := include "cas-server.mgmtname" . -}}
{{- $svcPort := .Values.mgmt.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cas-server.labels" . | nindent 4 }}
  {{- with .Values.mgmt.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.mgmt.ingress.tls }}
  tls:
    {{- range .Values.mgmt.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.mgmt.ingress.hosts }}
    - host: {{ include "cas-server.tplvalues.render" ( dict "value" .host "context" $ ) | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
